// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/proto/waffynx/v1/waffynx.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// -- Status --
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_waffynx_v1_waffynx_proto_rawDescGZIP(), []int{0}
}

type StatusResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Version           string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Running           bool                   `protobuf:"varint,2,opt,name=running,proto3" json:"running,omitempty"`
	UptimeSeconds     int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	RequestsTotal     uint64                 `protobuf:"varint,4,opt,name=requests_total,json=requestsTotal,proto3" json:"requests_total,omitempty"`
	BlockedTotal      uint64                 `protobuf:"varint,5,opt,name=blocked_total,json=blockedTotal,proto3" json:"blocked_total,omitempty"`
	ActiveConnections uint64                 `protobuf:"varint,6,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_waffynx_v1_waffynx_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StatusResponse) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *StatusResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *StatusResponse) GetRequestsTotal() uint64 {
	if x != nil {
		return x.RequestsTotal
	}
	return 0
}

func (x *StatusResponse) GetBlockedTotal() uint64 {
	if x != nil {
		return x.BlockedTotal
	}
	return 0
}

func (x *StatusResponse) GetActiveConnections() uint64 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

// -- Config --
type ReloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigPath    string                 `protobuf:"bytes,1,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadRequest) Reset() {
	*x = ReloadRequest{}
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadRequest) ProtoMessage() {}

func (x *ReloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadRequest.ProtoReflect.Descriptor instead.
func (*ReloadRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_waffynx_v1_waffynx_proto_rawDescGZIP(), []int{2}
}

func (x *ReloadRequest) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

type ReloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadResponse) Reset() {
	*x = ReloadResponse{}
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadResponse) ProtoMessage() {}

func (x *ReloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadResponse.ProtoReflect.Descriptor instead.
func (*ReloadResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_waffynx_v1_waffynx_proto_rawDescGZIP(), []int{3}
}

func (x *ReloadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReloadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// -- Policies --
type Policy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Phase         string                 `protobuf:"bytes,4,opt,name=phase,proto3" json:"phase,omitempty"`
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	Enabled       bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Conditions    []*Condition           `protobuf:"bytes,7,rep,name=conditions,proto3" json:"conditions,omitempty"`
	Action        string                 `protobuf:"bytes,8,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_pkg_proto_waffynx_v1_waffynx_proto_rawDescGZIP(), []int{4}
}

func (x *Policy) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Policy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Policy) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Policy) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *Policy) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Policy) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Policy) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *Policy) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type Condition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Operator      string                 `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Condition) Reset() {
	*x = Condition{}
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_pkg_proto_waffynx_v1_waffynx_proto_rawDescGZIP(), []int{5}
}

func (x *Condition) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Condition) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *Condition) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ListPoliciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoliciesRequest) Reset() {
	*x = ListPoliciesRequest{}
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesRequest) ProtoMessage() {}

func (x *ListPoliciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesRequest.ProtoReflect.Descriptor instead.
func (*ListPoliciesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_waffynx_v1_waffynx_proto_rawDescGZIP(), []int{6}
}

type ListPoliciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policies      []*Policy              `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoliciesResponse) Reset() {
	*x = ListPoliciesResponse{}
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesResponse) ProtoMessage() {}

func (x *ListPoliciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesResponse.ProtoReflect.Descriptor instead.
func (*ListPoliciesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_waffynx_v1_waffynx_proto_rawDescGZIP(), []int{7}
}

func (x *ListPoliciesResponse) GetPolicies() []*Policy {
	if x != nil {
		return x.Policies
	}
	return nil
}

type CreatePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy        *Policy                `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePolicyRequest) Reset() {
	*x = CreatePolicyRequest{}
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePolicyRequest) ProtoMessage() {}

func (x *CreatePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePolicyRequest.ProtoReflect.Descriptor instead.
func (*CreatePolicyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_waffynx_v1_waffynx_proto_rawDescGZIP(), []int{8}
}

func (x *CreatePolicyRequest) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type CreatePolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy        *Policy                `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePolicyResponse) Reset() {
	*x = CreatePolicyResponse{}
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePolicyResponse) ProtoMessage() {}

func (x *CreatePolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePolicyResponse.ProtoReflect.Descriptor instead.
func (*CreatePolicyResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_waffynx_v1_waffynx_proto_rawDescGZIP(), []int{9}
}

func (x *CreatePolicyResponse) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type UpdatePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy        *Policy                `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePolicyRequest) Reset() {
	*x = UpdatePolicyRequest{}
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePolicyRequest) ProtoMessage() {}

func (x *UpdatePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePolicyRequest.ProtoReflect.Descriptor instead.
func (*UpdatePolicyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_waffynx_v1_waffynx_proto_rawDescGZIP(), []int{10}
}

func (x *UpdatePolicyRequest) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type UpdatePolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy        *Policy                `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePolicyResponse) Reset() {
	*x = UpdatePolicyResponse{}
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePolicyResponse) ProtoMessage() {}

func (x *UpdatePolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePolicyResponse.ProtoReflect.Descriptor instead.
func (*UpdatePolicyResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_waffynx_v1_waffynx_proto_rawDescGZIP(), []int{11}
}

func (x *UpdatePolicyResponse) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type DeletePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePolicyRequest) Reset() {
	*x = DeletePolicyRequest{}
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePolicyRequest) ProtoMessage() {}

func (x *DeletePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePolicyRequest.ProtoReflect.Descriptor instead.
func (*DeletePolicyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_waffynx_v1_waffynx_proto_rawDescGZIP(), []int{12}
}

func (x *DeletePolicyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePolicyResponse) Reset() {
	*x = DeletePolicyResponse{}
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePolicyResponse) ProtoMessage() {}

func (x *DeletePolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePolicyResponse.ProtoReflect.Descriptor instead.
func (*DeletePolicyResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_waffynx_v1_waffynx_proto_rawDescGZIP(), []int{13}
}

func (x *DeletePolicyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// -- Routes --
type Route struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Methods       []string               `protobuf:"bytes,4,rep,name=methods,proto3" json:"methods,omitempty"`
	Upstream      string                 `protobuf:"bytes,5,opt,name=upstream,proto3" json:"upstream,omitempty"`
	Plugins       []string               `protobuf:"bytes,6,rep,name=plugins,proto3" json:"plugins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_pkg_proto_waffynx_v1_waffynx_proto_rawDescGZIP(), []int{14}
}

func (x *Route) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Route) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Route) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Route) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

func (x *Route) GetUpstream() string {
	if x != nil {
		return x.Upstream
	}
	return ""
}

func (x *Route) GetPlugins() []string {
	if x != nil {
		return x.Plugins
	}
	return nil
}

type ListRoutesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoutesRequest) Reset() {
	*x = ListRoutesRequest{}
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoutesRequest) ProtoMessage() {}

func (x *ListRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoutesRequest.ProtoReflect.Descriptor instead.
func (*ListRoutesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_waffynx_v1_waffynx_proto_rawDescGZIP(), []int{15}
}

type ListRoutesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routes        []*Route               `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoutesResponse) Reset() {
	*x = ListRoutesResponse{}
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoutesResponse) ProtoMessage() {}

func (x *ListRoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoutesResponse.ProtoReflect.Descriptor instead.
func (*ListRoutesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_waffynx_v1_waffynx_proto_rawDescGZIP(), []int{16}
}

func (x *ListRoutesResponse) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

type CreateRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Route         *Route                 `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRouteRequest) Reset() {
	*x = CreateRouteRequest{}
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRouteRequest) ProtoMessage() {}

func (x *CreateRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRouteRequest.ProtoReflect.Descriptor instead.
func (*CreateRouteRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_waffynx_v1_waffynx_proto_rawDescGZIP(), []int{17}
}

func (x *CreateRouteRequest) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

type CreateRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Route         *Route                 `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRouteResponse) Reset() {
	*x = CreateRouteResponse{}
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRouteResponse) ProtoMessage() {}

func (x *CreateRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRouteResponse.ProtoReflect.Descriptor instead.
func (*CreateRouteResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_waffynx_v1_waffynx_proto_rawDescGZIP(), []int{18}
}

func (x *CreateRouteResponse) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

type DeleteRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRouteRequest) Reset() {
	*x = DeleteRouteRequest{}
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRouteRequest) ProtoMessage() {}

func (x *DeleteRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRouteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRouteRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_waffynx_v1_waffynx_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteRouteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRouteResponse) Reset() {
	*x = DeleteRouteResponse{}
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRouteResponse) ProtoMessage() {}

func (x *DeleteRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRouteResponse.ProtoReflect.Descriptor instead.
func (*DeleteRouteResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_waffynx_v1_waffynx_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteRouteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// -- IP Management --
type BlockIPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	TtlSeconds    int32                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockIPRequest) Reset() {
	*x = BlockIPRequest{}
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockIPRequest) ProtoMessage() {}

func (x *BlockIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockIPRequest.ProtoReflect.Descriptor instead.
func (*BlockIPRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_waffynx_v1_waffynx_proto_rawDescGZIP(), []int{21}
}

func (x *BlockIPRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *BlockIPRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *BlockIPRequest) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type BlockIPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockIPResponse) Reset() {
	*x = BlockIPResponse{}
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockIPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockIPResponse) ProtoMessage() {}

func (x *BlockIPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockIPResponse.ProtoReflect.Descriptor instead.
func (*BlockIPResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_waffynx_v1_waffynx_proto_rawDescGZIP(), []int{22}
}

func (x *BlockIPResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UnblockIPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockIPRequest) Reset() {
	*x = UnblockIPRequest{}
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockIPRequest) ProtoMessage() {}

func (x *UnblockIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockIPRequest.ProtoReflect.Descriptor instead.
func (*UnblockIPRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_waffynx_v1_waffynx_proto_rawDescGZIP(), []int{23}
}

func (x *UnblockIPRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type UnblockIPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockIPResponse) Reset() {
	*x = UnblockIPResponse{}
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockIPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockIPResponse) ProtoMessage() {}

func (x *UnblockIPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockIPResponse.ProtoReflect.Descriptor instead.
func (*UnblockIPResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_waffynx_v1_waffynx_proto_rawDescGZIP(), []int{24}
}

func (x *UnblockIPResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// -- Marketplace --
type PackageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Author        string                 `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	Tags          []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	Downloads     int64                  `protobuf:"varint,8,opt,name=downloads,proto3" json:"downloads,omitempty"`
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageInfo) Reset() {
	*x = PackageInfo{}
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageInfo) ProtoMessage() {}

func (x *PackageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageInfo.ProtoReflect.Descriptor instead.
func (*PackageInfo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_waffynx_v1_waffynx_proto_rawDescGZIP(), []int{25}
}

func (x *PackageInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PackageInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PackageInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PackageInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PackageInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PackageInfo) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *PackageInfo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *PackageInfo) GetDownloads() int64 {
	if x != nil {
		return x.Downloads
	}
	return 0
}

func (x *PackageInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListPackagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPackagesRequest) Reset() {
	*x = ListPackagesRequest{}
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPackagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPackagesRequest) ProtoMessage() {}

func (x *ListPackagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPackagesRequest.ProtoReflect.Descriptor instead.
func (*ListPackagesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_waffynx_v1_waffynx_proto_rawDescGZIP(), []int{26}
}

func (x *ListPackagesRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListPackagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListPackagesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListPackagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packages      []*PackageInfo         `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPackagesResponse) Reset() {
	*x = ListPackagesResponse{}
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPackagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPackagesResponse) ProtoMessage() {}

func (x *ListPackagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPackagesResponse.ProtoReflect.Descriptor instead.
func (*ListPackagesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_waffynx_v1_waffynx_proto_rawDescGZIP(), []int{27}
}

func (x *ListPackagesResponse) GetPackages() []*PackageInfo {
	if x != nil {
		return x.Packages
	}
	return nil
}

type GetPackageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPackageRequest) Reset() {
	*x = GetPackageRequest{}
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackageRequest) ProtoMessage() {}

func (x *GetPackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackageRequest.ProtoReflect.Descriptor instead.
func (*GetPackageRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_waffynx_v1_waffynx_proto_rawDescGZIP(), []int{28}
}

func (x *GetPackageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetPackageRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetPackageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Package       *PackageInfo           `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPackageResponse) Reset() {
	*x = GetPackageResponse{}
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPackageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackageResponse) ProtoMessage() {}

func (x *GetPackageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackageResponse.ProtoReflect.Descriptor instead.
func (*GetPackageResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_waffynx_v1_waffynx_proto_rawDescGZIP(), []int{29}
}

func (x *GetPackageResponse) GetPackage() *PackageInfo {
	if x != nil {
		return x.Package
	}
	return nil
}

type InstallPackageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallPackageRequest) Reset() {
	*x = InstallPackageRequest{}
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallPackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallPackageRequest) ProtoMessage() {}

func (x *InstallPackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallPackageRequest.ProtoReflect.Descriptor instead.
func (*InstallPackageRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_waffynx_v1_waffynx_proto_rawDescGZIP(), []int{30}
}

func (x *InstallPackageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InstallPackageRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type InstallPackageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallPackageResponse) Reset() {
	*x = InstallPackageResponse{}
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallPackageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallPackageResponse) ProtoMessage() {}

func (x *InstallPackageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallPackageResponse.ProtoReflect.Descriptor instead.
func (*InstallPackageResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_waffynx_v1_waffynx_proto_rawDescGZIP(), []int{31}
}

func (x *InstallPackageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InstallPackageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UninstallPackageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UninstallPackageRequest) Reset() {
	*x = UninstallPackageRequest{}
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UninstallPackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UninstallPackageRequest) ProtoMessage() {}

func (x *UninstallPackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UninstallPackageRequest.ProtoReflect.Descriptor instead.
func (*UninstallPackageRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_waffynx_v1_waffynx_proto_rawDescGZIP(), []int{32}
}

func (x *UninstallPackageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UninstallPackageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UninstallPackageResponse) Reset() {
	*x = UninstallPackageResponse{}
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UninstallPackageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UninstallPackageResponse) ProtoMessage() {}

func (x *UninstallPackageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UninstallPackageResponse.ProtoReflect.Descriptor instead.
func (*UninstallPackageResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_waffynx_v1_waffynx_proto_rawDescGZIP(), []int{33}
}

func (x *UninstallPackageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UninstallPackageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SearchPackagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPackagesRequest) Reset() {
	*x = SearchPackagesRequest{}
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPackagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPackagesRequest) ProtoMessage() {}

func (x *SearchPackagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPackagesRequest.ProtoReflect.Descriptor instead.
func (*SearchPackagesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_waffynx_v1_waffynx_proto_rawDescGZIP(), []int{34}
}

func (x *SearchPackagesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SearchPackagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packages      []*PackageInfo         `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPackagesResponse) Reset() {
	*x = SearchPackagesResponse{}
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPackagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPackagesResponse) ProtoMessage() {}

func (x *SearchPackagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPackagesResponse.ProtoReflect.Descriptor instead.
func (*SearchPackagesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_waffynx_v1_waffynx_proto_rawDescGZIP(), []int{35}
}

func (x *SearchPackagesResponse) GetPackages() []*PackageInfo {
	if x != nil {
		return x.Packages
	}
	return nil
}

var File_pkg_proto_waffynx_v1_waffynx_proto protoreflect.FileDescriptor

const file_pkg_proto_waffynx_v1_waffynx_proto_rawDesc = "" +
	"\n" +
	"\"pkg/proto/waffynx/v1/waffynx.proto\x12\n" +
	"waffynx.v1\"\x0f\n" +
	"\rStatusRequest\"\xe6\x01\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x18\n" +
	"\arunning\x18\x02 \x01(\bR\arunning\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\x12%\n" +
	"\x0erequests_total\x18\x04 \x01(\x04R\rrequestsTotal\x12#\n" +
	"\rblocked_total\x18\x05 \x01(\x04R\fblockedTotal\x12-\n" +
	"\x12active_connections\x18\x06 \x01(\x04R\x11activeConnections\"0\n" +
	"\rReloadRequest\x12\x1f\n" +
	"\vconfig_path\x18\x01 \x01(\tR\n" +
	"configPath\"D\n" +
	"\x0eReloadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xe9\x01\n" +
	"\x06Policy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05phase\x18\x04 \x01(\tR\x05phase\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x125\n" +
	"\n" +
	"conditions\x18\a \x03(\v2\x15.waffynx.v1.ConditionR\n" +
	"conditions\x12\x16\n" +
	"\x06action\x18\b \x01(\tR\x06action\"S\n" +
	"\tCondition\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x1a\n" +
	"\boperator\x18\x02 \x01(\tR\boperator\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"\x15\n" +
	"\x13ListPoliciesRequest\"F\n" +
	"\x14ListPoliciesResponse\x12.\n" +
	"\bpolicies\x18\x01 \x03(\v2\x12.waffynx.v1.PolicyR\bpolicies\"A\n" +
	"\x13CreatePolicyRequest\x12*\n" +
	"\x06policy\x18\x01 \x01(\v2\x12.waffynx.v1.PolicyR\x06policy\"B\n" +
	"\x14CreatePolicyResponse\x12*\n" +
	"\x06policy\x18\x01 \x01(\v2\x12.waffynx.v1.PolicyR\x06policy\"A\n" +
	"\x13UpdatePolicyRequest\x12*\n" +
	"\x06policy\x18\x01 \x01(\v2\x12.waffynx.v1.PolicyR\x06policy\"B\n" +
	"\x14UpdatePolicyResponse\x12*\n" +
	"\x06policy\x18\x01 \x01(\v2\x12.waffynx.v1.PolicyR\x06policy\"%\n" +
	"\x13DeletePolicyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\x14DeletePolicyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x93\x01\n" +
	"\x05Route\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x18\n" +
	"\amethods\x18\x04 \x03(\tR\amethods\x12\x1a\n" +
	"\bupstream\x18\x05 \x01(\tR\bupstream\x12\x18\n" +
	"\aplugins\x18\x06 \x03(\tR\aplugins\"\x13\n" +
	"\x11ListRoutesRequest\"?\n" +
	"\x12ListRoutesResponse\x12)\n" +
	"\x06routes\x18\x01 \x03(\v2\x11.waffynx.v1.RouteR\x06routes\"=\n" +
	"\x12CreateRouteRequest\x12'\n" +
	"\x05route\x18\x01 \x01(\v2\x11.waffynx.v1.RouteR\x05route\">\n" +
	"\x13CreateRouteResponse\x12'\n" +
	"\x05route\x18\x01 \x01(\v2\x11.waffynx.v1.RouteR\x05route\"(\n" +
	"\x12DeleteRouteRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"/\n" +
	"\x13DeleteRouteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"Y\n" +
	"\x0eBlockIPRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x05R\n" +
	"ttlSeconds\"+\n" +
	"\x0fBlockIPResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\"\n" +
	"\x10UnblockIPRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\"-\n" +
	"\x11UnblockIPResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xeb\x01\n" +
	"\vPackageInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06author\x18\x05 \x01(\tR\x06author\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12\x1c\n" +
	"\tdownloads\x18\b \x01(\x03R\tdownloads\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\"_\n" +
	"\x13ListPackagesRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"K\n" +
	"\x14ListPackagesResponse\x123\n" +
	"\bpackages\x18\x01 \x03(\v2\x17.waffynx.v1.PackageInfoR\bpackages\"A\n" +
	"\x11GetPackageRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"G\n" +
	"\x12GetPackageResponse\x121\n" +
	"\apackage\x18\x01 \x01(\v2\x17.waffynx.v1.PackageInfoR\apackage\"E\n" +
	"\x15InstallPackageRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"L\n" +
	"\x16InstallPackageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"-\n" +
	"\x17UninstallPackageRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"N\n" +
	"\x18UninstallPackageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"-\n" +
	"\x15SearchPackagesRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"M\n" +
	"\x16SearchPackagesResponse\x123\n" +
	"\bpackages\x18\x01 \x03(\v2\x17.waffynx.v1.PackageInfoR\bpackages2\xdb\x06\n" +
	"\aWaffynx\x12B\n" +
	"\tGetStatus\x12\x19.waffynx.v1.StatusRequest\x1a\x1a.waffynx.v1.StatusResponse\x12E\n" +
	"\fReloadConfig\x12\x19.waffynx.v1.ReloadRequest\x1a\x1a.waffynx.v1.ReloadResponse\x12Q\n" +
	"\fListPolicies\x12\x1f.waffynx.v1.ListPoliciesRequest\x1a .waffynx.v1.ListPoliciesResponse\x12Q\n" +
	"\fCreatePolicy\x12\x1f.waffynx.v1.CreatePolicyRequest\x1a .waffynx.v1.CreatePolicyResponse\x12Q\n" +
	"\fUpdatePolicy\x12\x1f.waffynx.v1.UpdatePolicyRequest\x1a .waffynx.v1.UpdatePolicyResponse\x12Q\n" +
	"\fDeletePolicy\x12\x1f.waffynx.v1.DeletePolicyRequest\x1a .waffynx.v1.DeletePolicyResponse\x12K\n" +
	"\n" +
	"ListRoutes\x12\x1d.waffynx.v1.ListRoutesRequest\x1a\x1e.waffynx.v1.ListRoutesResponse\x12N\n" +
	"\vCreateRoute\x12\x1e.waffynx.v1.CreateRouteRequest\x1a\x1f.waffynx.v1.CreateRouteResponse\x12N\n" +
	"\vDeleteRoute\x12\x1e.waffynx.v1.DeleteRouteRequest\x1a\x1f.waffynx.v1.DeleteRouteResponse\x12B\n" +
	"\aBlockIP\x12\x1a.waffynx.v1.BlockIPRequest\x1a\x1b.waffynx.v1.BlockIPResponse\x12H\n" +
	"\tUnblockIP\x12\x1c.waffynx.v1.UnblockIPRequest\x1a\x1d.waffynx.v1.UnblockIPResponse2\xbe\x03\n" +
	"\vMarketplace\x12Q\n" +
	"\fListPackages\x12\x1f.waffynx.v1.ListPackagesRequest\x1a .waffynx.v1.ListPackagesResponse\x12K\n" +
	"\n" +
	"GetPackage\x12\x1d.waffynx.v1.GetPackageRequest\x1a\x1e.waffynx.v1.GetPackageResponse\x12W\n" +
	"\x0eInstallPackage\x12!.waffynx.v1.InstallPackageRequest\x1a\".waffynx.v1.InstallPackageResponse\x12]\n" +
	"\x10UninstallPackage\x12#.waffynx.v1.UninstallPackageRequest\x1a$.waffynx.v1.UninstallPackageResponse\x12W\n" +
	"\x0eSearchPackages\x12!.waffynx.v1.SearchPackagesRequest\x1a\".waffynx.v1.SearchPackagesResponseB2Z0github.com/jackby03/waffynx/pkg/proto/waffynx/v1b\x06proto3"

var (
	file_pkg_proto_waffynx_v1_waffynx_proto_rawDescOnce sync.Once
	file_pkg_proto_waffynx_v1_waffynx_proto_rawDescData []byte
)

func file_pkg_proto_waffynx_v1_waffynx_proto_rawDescGZIP() []byte {
	file_pkg_proto_waffynx_v1_waffynx_proto_rawDescOnce.Do(func() {
		file_pkg_proto_waffynx_v1_waffynx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_waffynx_v1_waffynx_proto_rawDesc), len(file_pkg_proto_waffynx_v1_waffynx_proto_rawDesc)))
	})
	return file_pkg_proto_waffynx_v1_waffynx_proto_rawDescData
}

var file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_pkg_proto_waffynx_v1_waffynx_proto_goTypes = []any{
	(*StatusRequest)(nil),            // 0: waffynx.v1.StatusRequest
	(*StatusResponse)(nil),           // 1: waffynx.v1.StatusResponse
	(*ReloadRequest)(nil),            // 2: waffynx.v1.ReloadRequest
	(*ReloadResponse)(nil),           // 3: waffynx.v1.ReloadResponse
	(*Policy)(nil),                   // 4: waffynx.v1.Policy
	(*Condition)(nil),                // 5: waffynx.v1.Condition
	(*ListPoliciesRequest)(nil),      // 6: waffynx.v1.ListPoliciesRequest
	(*ListPoliciesResponse)(nil),     // 7: waffynx.v1.ListPoliciesResponse
	(*CreatePolicyRequest)(nil),      // 8: waffynx.v1.CreatePolicyRequest
	(*CreatePolicyResponse)(nil),     // 9: waffynx.v1.CreatePolicyResponse
	(*UpdatePolicyRequest)(nil),      // 10: waffynx.v1.UpdatePolicyRequest
	(*UpdatePolicyResponse)(nil),     // 11: waffynx.v1.UpdatePolicyResponse
	(*DeletePolicyRequest)(nil),      // 12: waffynx.v1.DeletePolicyRequest
	(*DeletePolicyResponse)(nil),     // 13: waffynx.v1.DeletePolicyResponse
	(*Route)(nil),                    // 14: waffynx.v1.Route
	(*ListRoutesRequest)(nil),        // 15: waffynx.v1.ListRoutesRequest
	(*ListRoutesResponse)(nil),       // 16: waffynx.v1.ListRoutesResponse
	(*CreateRouteRequest)(nil),       // 17: waffynx.v1.CreateRouteRequest
	(*CreateRouteResponse)(nil),      // 18: waffynx.v1.CreateRouteResponse
	(*DeleteRouteRequest)(nil),       // 19: waffynx.v1.DeleteRouteRequest
	(*DeleteRouteResponse)(nil),      // 20: waffynx.v1.DeleteRouteResponse
	(*BlockIPRequest)(nil),           // 21: waffynx.v1.BlockIPRequest
	(*BlockIPResponse)(nil),          // 22: waffynx.v1.BlockIPResponse
	(*UnblockIPRequest)(nil),         // 23: waffynx.v1.UnblockIPRequest
	(*UnblockIPResponse)(nil),        // 24: waffynx.v1.UnblockIPResponse
	(*PackageInfo)(nil),              // 25: waffynx.v1.PackageInfo
	(*ListPackagesRequest)(nil),      // 26: waffynx.v1.ListPackagesRequest
	(*ListPackagesResponse)(nil),     // 27: waffynx.v1.ListPackagesResponse
	(*GetPackageRequest)(nil),        // 28: waffynx.v1.GetPackageRequest
	(*GetPackageResponse)(nil),       // 29: waffynx.v1.GetPackageResponse
	(*InstallPackageRequest)(nil),    // 30: waffynx.v1.InstallPackageRequest
	(*InstallPackageResponse)(nil),   // 31: waffynx.v1.InstallPackageResponse
	(*UninstallPackageRequest)(nil),  // 32: waffynx.v1.UninstallPackageRequest
	(*UninstallPackageResponse)(nil), // 33: waffynx.v1.UninstallPackageResponse
	(*SearchPackagesRequest)(nil),    // 34: waffynx.v1.SearchPackagesRequest
	(*SearchPackagesResponse)(nil),   // 35: waffynx.v1.SearchPackagesResponse
}
var file_pkg_proto_waffynx_v1_waffynx_proto_depIdxs = []int32{
	5,  // 0: waffynx.v1.Policy.conditions:type_name -> waffynx.v1.Condition
	4,  // 1: waffynx.v1.ListPoliciesResponse.policies:type_name -> waffynx.v1.Policy
	4,  // 2: waffynx.v1.CreatePolicyRequest.policy:type_name -> waffynx.v1.Policy
	4,  // 3: waffynx.v1.CreatePolicyResponse.policy:type_name -> waffynx.v1.Policy
	4,  // 4: waffynx.v1.UpdatePolicyRequest.policy:type_name -> waffynx.v1.Policy
	4,  // 5: waffynx.v1.UpdatePolicyResponse.policy:type_name -> waffynx.v1.Policy
	14, // 6: waffynx.v1.ListRoutesResponse.routes:type_name -> waffynx.v1.Route
	14, // 7: waffynx.v1.CreateRouteRequest.route:type_name -> waffynx.v1.Route
	14, // 8: waffynx.v1.CreateRouteResponse.route:type_name -> waffynx.v1.Route
	25, // 9: waffynx.v1.ListPackagesResponse.packages:type_name -> waffynx.v1.PackageInfo
	25, // 10: waffynx.v1.GetPackageResponse.package:type_name -> waffynx.v1.PackageInfo
	25, // 11: waffynx.v1.SearchPackagesResponse.packages:type_name -> waffynx.v1.PackageInfo
	0,  // 12: waffynx.v1.Waffynx.GetStatus:input_type -> waffynx.v1.StatusRequest
	2,  // 13: waffynx.v1.Waffynx.ReloadConfig:input_type -> waffynx.v1.ReloadRequest
	6,  // 14: waffynx.v1.Waffynx.ListPolicies:input_type -> waffynx.v1.ListPoliciesRequest
	8,  // 15: waffynx.v1.Waffynx.CreatePolicy:input_type -> waffynx.v1.CreatePolicyRequest
	10, // 16: waffynx.v1.Waffynx.UpdatePolicy:input_type -> waffynx.v1.UpdatePolicyRequest
	12, // 17: waffynx.v1.Waffynx.DeletePolicy:input_type -> waffynx.v1.DeletePolicyRequest
	15, // 18: waffynx.v1.Waffynx.ListRoutes:input_type -> waffynx.v1.ListRoutesRequest
	17, // 19: waffynx.v1.Waffynx.CreateRoute:input_type -> waffynx.v1.CreateRouteRequest
	19, // 20: waffynx.v1.Waffynx.DeleteRoute:input_type -> waffynx.v1.DeleteRouteRequest
	21, // 21: waffynx.v1.Waffynx.BlockIP:input_type -> waffynx.v1.BlockIPRequest
	23, // 22: waffynx.v1.Waffynx.UnblockIP:input_type -> waffynx.v1.UnblockIPRequest
	26, // 23: waffynx.v1.Marketplace.ListPackages:input_type -> waffynx.v1.ListPackagesRequest
	28, // 24: waffynx.v1.Marketplace.GetPackage:input_type -> waffynx.v1.GetPackageRequest
	30, // 25: waffynx.v1.Marketplace.InstallPackage:input_type -> waffynx.v1.InstallPackageRequest
	32, // 26: waffynx.v1.Marketplace.UninstallPackage:input_type -> waffynx.v1.UninstallPackageRequest
	34, // 27: waffynx.v1.Marketplace.SearchPackages:input_type -> waffynx.v1.SearchPackagesRequest
	1,  // 28: waffynx.v1.Waffynx.GetStatus:output_type -> waffynx.v1.StatusResponse
	3,  // 29: waffynx.v1.Waffynx.ReloadConfig:output_type -> waffynx.v1.ReloadResponse
	7,  // 30: waffynx.v1.Waffynx.ListPolicies:output_type -> waffynx.v1.ListPoliciesResponse
	9,  // 31: waffynx.v1.Waffynx.CreatePolicy:output_type -> waffynx.v1.CreatePolicyResponse
	11, // 32: waffynx.v1.Waffynx.UpdatePolicy:output_type -> waffynx.v1.UpdatePolicyResponse
	13, // 33: waffynx.v1.Waffynx.DeletePolicy:output_type -> waffynx.v1.DeletePolicyResponse
	16, // 34: waffynx.v1.Waffynx.ListRoutes:output_type -> waffynx.v1.ListRoutesResponse
	18, // 35: waffynx.v1.Waffynx.CreateRoute:output_type -> waffynx.v1.CreateRouteResponse
	20, // 36: waffynx.v1.Waffynx.DeleteRoute:output_type -> waffynx.v1.DeleteRouteResponse
	22, // 37: waffynx.v1.Waffynx.BlockIP:output_type -> waffynx.v1.BlockIPResponse
	24, // 38: waffynx.v1.Waffynx.UnblockIP:output_type -> waffynx.v1.UnblockIPResponse
	27, // 39: waffynx.v1.Marketplace.ListPackages:output_type -> waffynx.v1.ListPackagesResponse
	29, // 40: waffynx.v1.Marketplace.GetPackage:output_type -> waffynx.v1.GetPackageResponse
	31, // 41: waffynx.v1.Marketplace.InstallPackage:output_type -> waffynx.v1.InstallPackageResponse
	33, // 42: waffynx.v1.Marketplace.UninstallPackage:output_type -> waffynx.v1.UninstallPackageResponse
	35, // 43: waffynx.v1.Marketplace.SearchPackages:output_type -> waffynx.v1.SearchPackagesResponse
	28, // [28:44] is the sub-list for method output_type
	12, // [12:28] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_pkg_proto_waffynx_v1_waffynx_proto_init() }
func file_pkg_proto_waffynx_v1_waffynx_proto_init() {
	if File_pkg_proto_waffynx_v1_waffynx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_waffynx_v1_waffynx_proto_rawDesc), len(file_pkg_proto_waffynx_v1_waffynx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pkg_proto_waffynx_v1_waffynx_proto_goTypes,
		DependencyIndexes: file_pkg_proto_waffynx_v1_waffynx_proto_depIdxs,
		MessageInfos:      file_pkg_proto_waffynx_v1_waffynx_proto_msgTypes,
	}.Build()
	File_pkg_proto_waffynx_v1_waffynx_proto = out.File
	file_pkg_proto_waffynx_v1_waffynx_proto_goTypes = nil
	file_pkg_proto_waffynx_v1_waffynx_proto_depIdxs = nil
}
